# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.4.1-node-browsers
        environment:
          BUNDLER_VERSION: 2.0.2

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      # run tests!
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            rake spec

  publish:
    name: Publish artifacts
    steps:
      - checkout

      - gem_release
        name: Release gem
        command: |
          scripts/minor.sh

      - docker_release
        name: Trigger docker remotely
        command: curl --data build=true -X POST https://registry.hub.docker.com/u/svendowideit/testhook/trigger/be579c82-7c0e-11e4-81c4-0242ac110020/

workflows:
  version: 2
  build_and_publish:
    jobs:
      - build
      - publish
        filters:
          branches:
            only:
              - master
              - publish_gem

