# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.4.1-node-browsers
        environment:
          BUNDLER_VERSION: 2.0.2

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      # run tests!
      - run:
          name: run tests
          command: |-
            mkdir /tmp/test-results
            rake spec

  publish:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.4.1-node-browsers
    steps:
      - checkout

      - gem_release:
          name: 'Release'
          command: |
            scripts/minor.sh

      - docker_release:
          command: curl --data build=true -X POST https://cloud.docker.com/api/build/v1/source/06910a8b-39e1-4929-b55c-4111c3216452/trigger/24b37a19-bd4c-461d-ba80-3d9f1b0704bd/call/

workflows:
  version: 2
  build_and_publish:
    jobs:
      - build
      - publish:
          filters:
            branches:
              only:
                - master
                - publish_gem

